{{- range $entry := .Values.servers }}
---
apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Pool
metadata:
  name: {{ include "openvox-stack.poolName" (dict "root" $ "entry" $entry) }}
spec:
  environmentRef: {{ include "openvox-stack.envName" $ }}
  selector:
    openvox.voxpupuli.org/server: {{ include "openvox-stack.serverName" (dict "root" $ "entry" $entry) }}
  service:
    type: {{ (dig "pool" "service" "type" "ClusterIP" $entry) }}
    port: {{ (dig "pool" "service" "port" 8140 $entry) }}
{{- end }}
