{{- range $entry := .Values.pools }}
---
apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Pool
metadata:
  name: {{ include "openvox-stack.poolName" (dict "root" $ "entry" $entry) }}
spec:
  environmentRef: {{ include "openvox-stack.envName" $ }}
  selector:
    openvox.voxpupuli.org/server: {{ include "openvox-stack.serverName" (dict "root" $ "entry" (dict "name" $entry.serverRef)) }}
  service:
    type: {{ $entry.service.type | default "ClusterIP" }}
    port: {{ $entry.service.port | default 8140 }}
{{- end }}
