# Rootless OpenVox CodeDeploy on UBI9 for Kubernetes/OpenShift
# Runs r10k for Puppet code deployment from Git repositories.
#
# Build (from repo root):
#   podman build -t openvox-codedeploy:latest -f images/openvox-codedeploy/Containerfile .
#
# Run:
#   podman run --rm openvox-codedeploy:latest deploy environment -pv

# renovate: datasource=rubygems depName=r10k
ARG R10K_VERSION=4.1.0

FROM registry.access.redhat.com/ubi9/ubi:9.7-1771346757

ARG R10K_VERSION

LABEL org.opencontainers.image.title="OpenVox CodeDeploy" \
      org.opencontainers.image.description="Rootless r10k code deployment for Kubernetes/OpenShift" \
      org.opencontainers.image.vendor="slauger" \
      org.opencontainers.image.url="https://github.com/slauger/openvox-operator" \
      org.opencontainers.image.source="https://github.com/slauger/openvox-operator" \
      org.opencontainers.image.licenses="Apache-2.0"

# System Ruby 3.3, r10k dependencies, and Git/SSH tools
RUN dnf module enable ruby:3.3 -y \
    && dnf install -y --setopt=install_weak_deps=False \
        ruby \
        ruby-devel \
        gcc \
        make \
        redhat-rpm-config \
        git \
        openssh-clients \
    && gem install --no-document r10k -v "${R10K_VERSION}" \
    && dnf remove -y gcc make ruby-devel redhat-rpm-config \
    && dnf clean all

# r10k basedir (default target for deployed environments)
RUN install -d -m 0775 -g 0 /etc/puppetlabs/code/environments \
    && install -d -m 0775 -g 0 /etc/puppetlabs/r10k \
    && install -d -m 0775 -g 0 /opt/puppetlabs/r10k/cache \
    && install -d -m 0775 -g 0 /home/codedeploy

# OpenShift random-UID pattern: group=root(0), mirror user perms to group
# /etc/passwd must be group-writable so entrypoint can inject the random UID
RUN chmod g=u /etc/passwd \
    && for d in \
        /etc/puppetlabs \
        /opt/puppetlabs \
        /home/codedeploy \
    ; do \
        chgrp -R 0 "$d"; \
        chmod -R g=u "$d"; \
        find "$d" -type d -exec chmod g+s {} +; \
    done

COPY images/openvox-codedeploy/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV HOME=/home/codedeploy

USER 1001:0

ENTRYPOINT ["/entrypoint.sh"]
CMD ["deploy", "environment", "-pv"]
