services:
  openvoxserver:
    build:
      context: ../images/openvoxserver
      dockerfile: Containerfile
    hostname: puppet
    ports:
      - "8140:8140"
    environment:
      - USE_OPENVOXDB=true
      - OPENVOXDB_SERVER_URLS=https://openvoxdb:8081
      - AUTOSIGN=true
      - OPENVOXSERVER_JAVA_ARGS=-Xms1024m -Xmx1024m
    volumes:
      - puppet-code:/etc/puppetlabs/code
      - puppet-ssl:/etc/puppetlabs/puppet/ssl
      - puppet-ca:/etc/puppetlabs/puppetserver/ca
      - puppet-data:/opt/puppetlabs/server/data/puppetserver
    # rootless — no need for privileged or root
    user: "1001:0"

  openvoxdb:
    image: ghcr.io/openvoxproject/container-openvoxdb:latest
    hostname: openvoxdb
    environment:
      - CERTNAME=openvoxdb
    volumes:
      - openvoxdb-data:/opt/puppetlabs/server/data/puppetdb
      - openvoxdb-ssl:/etc/puppetlabs/puppet/ssl

volumes:
  puppet-code:
  puppet-ssl:
  puppet-ca:
  puppet-data:
  openvoxdb-data:
  openvoxdb-ssl:
